version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: nastyxxaavs_user
      POSTGRES_PASSWORD: 2bHktO83QaYtLS0cCa01ZM3gpkPjPpEY
      POSTGRES_DB: nastyxxaavs
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
